name = "SkyBlock Enhanced"
author = "Kd_Gaming1"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ad1f20dd0aa09da1201998044aa6e1e48ba285654c2a3940cc18e919726e1cb"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
