name = "SkyBlock Enhanced – Modern Edition"
author = "Kd_Gaming1"
version = "0.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23c3a46241c58ea0b4b691d011196f8c6d434a1d27ba054ccec1ecc5ba8317ba"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
