name = "SkyBlock Enhanced"
author = "Kd_Gaming1"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8217a5202cb011591ffe7fee723203fe103912bd5c0bd1b30519f2edc91b72d0"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
